version: '3.8'

services:
  web:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: deployments/compose/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - ${PORT:-8001}:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: rtmbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1253'
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: deployments/compose/bot/Dockerfile
    command: python apps/bot/main.py
    volumes:
      - .:/app
    depends_on:
      - web
    restart: always


volumes:
  pg_data:
