# Generated by Django 5.0.8 on 2024-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="language_code",
            field=models.CharField(
                choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                default="uz",
                max_length=10,
                verbose_name="Til",
            ),
        ),
    ]
