# Generated by Django 5.0.8 on 2024-11-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0002_alter_botusers_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rtm.region",
                verbose_name="Viloyat",
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rtm.science",
                verbose_name="Fan",
            ),
        ),
    ]
