# Generated by Django 5.0.8 on 2024-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0003_alter_botusers_region_alter_botusers_science"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Viloyat nomi"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Viloyat nomi"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Viloyat nomi"
            ),
        ),
        migrations.AddField(
            model_name="science",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Fan nomi"),
        ),
        migrations.AddField(
            model_name="science",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Fan nomi"),
        ),
        migrations.AddField(
            model_name="science",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Fan nomi"),
        ),
    ]
