# Generated by Django 5.0.8 on 2024-11-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0004_region_name_en_region_name_ru_region_name_uz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="science",
            name="name_en",
        ),
    ]
