# Generated by Django 5.0.8 on 2024-11-11 08:30

import apps.rtm.models.messages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0005_remove_region_name_en_remove_science_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="answers",
                validators=[apps.rtm.models.messages.validate_image_size],
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="messages",
                validators=[apps.rtm.models.messages.validate_image_size],
                verbose_name="Rasm",
            ),
        ),
    ]
