# Generated by Django 5.0.8 on 2024-11-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0006_alter_answer_image_alter_messages_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="messages", verbose_name="Rasm"
            ),
        ),
    ]
