# Generated by Django 5.0.8 on 2024-11-11 09:35

import apps.rtm.models.messages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtm", "0007_alter_messages_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="messages",
                validators=[apps.rtm.models.messages.validate_image_size],
                verbose_name="Rasm",
            ),
        ),
    ]
